version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@CYLINRAf45
      - POSTGRES_DB=friendship_test_db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/friendshiptest
    ports:
      - "8000:8000"
    env_file:
      - ./friendshiptest/.env
    depends_on:
      - db
